CREATE TABLE IF NOT EXISTS Users (
  about VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  fullname VARCHAR(100) UNIQUE,
  nickname VARCHAR(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Forums (
  slug VARCHAR(100) PRIMARY KEY NOT NULL,
  title VARCHAR(100) UNIQUE NOT NULL,
  author VARCHAR(100) NOT NULL,
  FOREIGN KEY (author) REFERENCES Users (nickname)
);

CREATE TABLE IF NOT EXISTS ForumSlugs (
  author VARCHAR(100) NOT NULL,
  FOREIGN KEY (author) REFERENCES Users(nickname),
  forum VARCHAR(100) NOT NULL,
  FOREIGN KEY (forum) REFERENCES Forums(slug),
  slug VARCHAR(100) PRIMARY KEY NOT NULL,
  title VARCHAR(100) UNIQUE NOT NULL
);