CREATE TABLE IF NOT EXISTS Users (
  about VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  fullname VARCHAR(100) UNIQUE,
  nickname VARCHAR(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Forums (
  posts BIGINT DEFAULT 0,
  slug VARCHAR(100) PRIMARY KEY NOT NULL,
  threads BIGINT DEFAULT 0,
  title VARCHAR(100) UNIQUE NOT NULL,
  "user" VARCHAR(100) NOT NULL,
  FOREIGN KEY ("user") REFERENCES Users (nickname)
);

CREATE TABLE IF NOT EXISTS ForumSlugs (
  author VARCHAR(100) NOT NULL,
  FOREIGN KEY (author) REFERENCES Users(nickname),
  created VARCHAR(100) DEFAULT 0,
  forum VARCHAR(100) NOT NULL,
  FOREIGN KEY (forum) REFERENCES Forums(slug),
  id BIGINT DEFAULT 0,
  message VARCHAR(100),
  slug VARCHAR(100) PRIMARY KEY NOT NULL,
  title VARCHAR(100) UNIQUE NOT NULL,
  votes BIGINT DEFAULT 0
);